version: '3.5'

services:
  app:
    container_name: mllefantasia_siteweb
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - 80
    env_file:
      - .env

networks:
    default:
       external:
         name: webproxy

